# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booked',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
