# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_ticket_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
