# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20160314_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booked',
            field=models.IntegerField(),
        ),
    ]
