# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20160315_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booked',
            field=models.CharField(blank=True, default='YES', max_length=100),
        ),
    ]
