# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20160315_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booked',
            field=models.BooleanField(),
        ),
    ]
